# Generated by Django 3.1.5 on 2021-01-09 06:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210108_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 12, 29, 52, 63339)),
        ),
        migrations.AlterField(
            model_name='branch',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 12, 29, 52, 57350)),
        ),
        migrations.AlterField(
            model_name='college',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 12, 29, 52, 56322)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 12, 29, 52, 61337)),
        ),
        migrations.AlterField(
            model_name='proctor',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 12, 29, 52, 59344)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 12, 29, 52, 62334)),
        ),
        migrations.AlterField(
            model_name='students',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 12, 29, 52, 60341)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 12, 29, 52, 58309)),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=100)),
                ('doc', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 12, 29, 52, 59344))),
                ('slug', models.SlugField()),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.college')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='semester_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='App.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='semester_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='App.semester'),
            preserve_default=False,
        ),
    ]
