# Generated by Django 3.1.5 on 2021-01-14 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210111_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 16, 40, 9, 394242)),
        ),
        migrations.AlterField(
            model_name='branch',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 16, 40, 9, 370296)),
        ),
        migrations.AlterField(
            model_name='college',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 16, 40, 9, 366979)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 16, 40, 9, 386716)),
        ),
        migrations.AlterField(
            model_name='proctor',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 16, 40, 9, 377736)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 16, 40, 9, 390709)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='marks',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_a',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_b',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_c',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_d',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='section',
            field=models.CharField(choices=[('all', 'All'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=500),
        ),
        migrations.AlterField(
            model_name='semester',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 16, 40, 9, 375892)),
        ),
        migrations.AlterField(
            model_name='students',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 16, 40, 9, 379527)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 16, 40, 9, 373082)),
        ),
    ]
