# Generated by Django 3.1.5 on 2021-01-14 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210114_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 17, 13, 27, 971998)),
        ),
        migrations.AlterField(
            model_name='branch',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 17, 13, 27, 957038)),
        ),
        migrations.AlterField(
            model_name='college',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 17, 13, 27, 948063)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 17, 13, 27, 966015)),
        ),
        migrations.AlterField(
            model_name='proctor',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 17, 13, 27, 962024)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 17, 13, 27, 969008)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_d',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 17, 13, 27, 960029)),
        ),
        migrations.AlterField(
            model_name='students',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 17, 13, 27, 964019)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 17, 13, 27, 959033)),
        ),
    ]
