# Generated by Django 3.1.5 on 2021-01-21 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20210117_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctor',
            name='assign_section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 23, 21, 17, 488715)),
        ),
        migrations.AlterField(
            model_name='branch',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 23, 21, 17, 476793)),
        ),
        migrations.AlterField(
            model_name='college',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 23, 21, 17, 475788)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 23, 21, 17, 481209)),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='proctor_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='proctor_id',
            field=models.ManyToManyField(blank=True, to='App.Proctor'),
        ),
        migrations.AlterField(
            model_name='proctor',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 23, 21, 17, 481209)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 23, 21, 17, 487715)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='section',
            field=models.CharField(choices=[('ALL', 'ALL'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 23, 21, 17, 480212)),
        ),
        migrations.AlterField(
            model_name='students',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 23, 21, 17, 481209)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 23, 21, 17, 478476)),
        ),
    ]
